services:
  proxy:
    ports:
      - "28080:28080"
    container_name: proxy
    env_file:
      - .env
    build:
      context: .
      dockerfile: proxy/Dockerfile
    depends_on:
      - simple_bot
      - smart_bot
      - ai_bot
    restart: unless-stopped
    networks:
      - sea_battle

  simple_bot:
    ports:
      - "8081:28080"
    container_name: simple_bot
    build:
      context: .
      dockerfile: simple_bot/Dockerfile
    restart: unless-stopped
    networks:
      - sea_battle

  smart_bot:
    ports:
      - "8082:28080"
    container_name: smart_bot
    env_file:
      - smart_bot/.env
    build:
      context: .
      dockerfile: smart_bot/Dockerfile
    restart: unless-stopped
    networks:
      - sea_battle

  ai_bot:
    ports:
      - "8083:28080"
    container_name: ai_bot
    build:
      context: .
      dockerfile: ai_bot/Dockerfile
    restart: unless-stopped
    networks:
      - sea_battle

networks:
  sea_battle:
    driver: bridge